CREATE TABLE "USER" (
  "ID" "VARCHAR" PRIMARY KEY,
  "FIRST_NAME" "VARCHAR",
  "LAST_NAME" "VARCHAR",
  "EMAIL_ADDRESS" "VARCHAR",
  "CREATED_ON" "TIMESTAMP",
  "CREATED_BY" "VARCHAR",
  "MODIFIED_ON" "TIMESTAMP",
  "MODIFIED_BY" "VARCHAR"
);

CREATE TABLE "USER_LOGIN_DETAIL" (
  "ID" "VARCHAR" PRIMARY KEY,
  "ID_USER_DETAIL" "VARCHAR",
  "FIRST_NAME" "VARCHAR",
  "LAST_NAME" "VARCHAR",
  "EMAIL_ADDRESS" "VARCHAR",
  "USER_STATUS" "VARCHAR",
  "CREATED_ON" "TIMESTAMP",
  "CREATED_BY" "VARCHAR",
  "MODIFIED_ON" "TIMESTAMP",
  "MODIFIED_BY" "VARCHAR"
);

CREATE TABLE "ORDER_DETAIL" (
  "ID" "VARCHAR" PRIMARY KEY,
  "ID_SECURITY_DETAIL" "VARCHAR",
  "ORDER_REF_NO" "VARCHAR",
  "ORDER_STATUS" "VARCHAR",
  "TRANSACTION_TYPE" "VARCHAR",
  "ORDER_VALUE" "VARCHAR",
  "CREATED_ON" "TIMESTAMP",
  "CREATED_BY" "VARCHAR"
);

CREATE TABLE "ACCOUNT_DETAIL" (
  "ID" "INT" PRIMARY KEY,
  "ID_USER_LOGIN_DETAIL" "INT",
  "CREDIT" "INT",
  "DEBIT" "INT",
  "RUNNING_BALANCE" "INT" DEFAULT 10000,
  "ID_ORDER_DETAIL" "INT",
  "CREATED_ON" "TIMESTAMP",
  "CREATED_BY" "INT"
);

CREATE TABLE "SECURITY_DETAIL" (
  "ID" "INT" PRIMARY KEY,
  "SECURITY_NAME" "INT",
  "VALUE" "INT"
);

CREATE TABLE "AUDIT_USER_LOGIN" (
  "ID" "INT" PRIMARY KEY,
  "ID_USER_LOGIN_DETAIL" "INT",
  "SESSION_ID" "VARCHAR",
  "LOGIN_STATUS" "VARCHAR",
  "LOGIN_DATE_TIME" "TIMESTAMP",
  "LOGOUT_DATE_TIME" "TIMESTAMP"
);

CREATE TABLE "AUDIT_ACTION" (
  "ID" "INT" PRIMARY KEY,
  "ID_USER_LOGIN_DETAIL" "INT",
  "USER_ACTION" "VARCHAR",
  "START_DATE_TIME" "TIMESTAMP",
  "END_DATE_TIME" "TIMESTAMP"
);

ALTER TABLE "USER_LOGIN_DETAIL" ADD FOREIGN KEY ("ID_USER_DETAIL") REFERENCES "USER" ("ID");

ALTER TABLE "ORDER_DETAIL" ADD FOREIGN KEY ("ID_SECURITY_DETAIL") REFERENCES "SECURITY_DETAIL" ("ID");

ALTER TABLE "ORDER_DETAIL" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "USER_LOGIN_DETAIL" ("ID");

ALTER TABLE "ACCOUNT_DETAIL" ADD FOREIGN KEY ("ID_USER_LOGIN_DETAIL") REFERENCES "USER_LOGIN_DETAIL" ("ID");

ALTER TABLE "ACCOUNT_DETAIL" ADD FOREIGN KEY ("ID_ORDER_DETAIL") REFERENCES "ORDER_DETAIL" ("ID");

ALTER TABLE "ACCOUNT_DETAIL" ADD FOREIGN KEY ("CREATED_BY") REFERENCES "USER_LOGIN_DETAIL" ("ID");

ALTER TABLE "SECURITY_DETAIL" ADD FOREIGN KEY ("SECURITY_NAME") REFERENCES "SECURITY_DETAIL" ("ID");

ALTER TABLE "AUDIT_USER_LOGIN" ADD FOREIGN KEY ("ID_USER_LOGIN_DETAIL") REFERENCES "USER_LOGIN_DETAIL" ("ID");

ALTER TABLE "AUDIT_ACTION" ADD FOREIGN KEY ("ID_USER_LOGIN_DETAIL") REFERENCES "USER_LOGIN_DETAIL" ("ID");

ALTER TABLE "ACCOUNT_DETAIL" ADD FOREIGN KEY ("ID") REFERENCES "ACCOUNT_DETAIL" ("ID_USER_LOGIN_DETAIL");
